language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

matrix:
  exclude:
    - php: '5.4'
      env: SYMFONY_VERSION="3.0.*"
    - php: '5.4'
      env: SYMFONY_VERSION="3.1.*"

notifications:
  email:
    - me@daken.ru