language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"

before_script:
  - if [[ $(phpenv version-name) != "hhvm" ]] then ((echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini)) fi
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  exclude:
    - php: '5.4'
      env: SYMFONY_VERSION="3.0.*"
    - php: '5.4'
      env: SYMFONY_VERSION="3.1.*"

notifications:
  email:
    - me@daken.ru